apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: embeddings
  namespace: sovereignty-ai-dev
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "image-registry.openshift-image-registry.svc:5000/sovereignty-ai-dev/embeddings:latest"
