apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: embeddings-build
  namespace: sovereignty-ai-dev
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: embeddings/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: embeddings:latest
